const searchForm = document.getElementById('searchForm');
const cityInput = document.getElementById('cityInput');
const statusMessage = document.getElementById('statusMessage');
const weatherInfo = document.getElementById('weatherInfo');
const weatherCodes = { 0:['Clear sky','☀'],1:['Mainly clear','◐'],2:['Partly cloudy','◒'],3:['Overcast','☁'],45:['Foggy','≋'],48:['Rime fog','≋'],51:['Light drizzle','⋰'],53:['Drizzle','⋰'],55:['Dense drizzle','⋰'],61:['Light rain','☂'],63:['Rain','☂'],65:['Heavy rain','☂'],71:['Light snow','❄'],73:['Snow','❄'],75:['Heavy snow','❄'],80:['Rain showers','☂'],81:['Rain showers','☂'],82:['Heavy showers','☂'],95:['Thunderstorm','ϟ'],96:['Thunderstorm','ϟ'],99:['Thunderstorm','ϟ'] };
const formatDay = (date, index) => index === 0 ? 'Today' : new Date(`${date}T12:00:00`).toLocaleDateString('en-US', { weekday:'short' });
const getWeather = code => weatherCodes[code] || ['Changing skies','◒'];
function renderForecast(data) { document.getElementById('forecastList').innerHTML = data.daily.time.slice(0,5).map((date,index) => { const [description,icon] = getWeather(data.daily.weather_code[index]); return `<div class="forecast-day"><span class="day">${formatDay(date,index)}</span><span class="forecast-icon" aria-label="${description}">${icon}</span><span>${description}</span><strong class="forecast-range">${Math.round(data.daily.temperature_2m_max[index])}° <span>${Math.round(data.daily.temperature_2m_min[index])}°</span></strong></div>`; }).join(''); }
function renderWeather(location,data) { const [description,icon] = getWeather(data.current.weather_code); document.getElementById('cityName').textContent=location.name; document.getElementById('locationDetail').textContent=`${location.name}, ${location.country}`; document.getElementById('weatherIcon').textContent=icon; document.getElementById('temperature').textContent=`${Math.round(data.current.temperature_2m)}°`; document.getElementById('description').textContent=description; document.getElementById('feelsLike').textContent=`${Math.round(data.current.apparent_temperature)}°`; document.getElementById('wind').textContent=`${Math.round(data.current.wind_speed_10m)} km/h`; document.getElementById('humidity').textContent=`${data.current.relative_humidity_2m}%`; document.getElementById('visibility').textContent=`${(data.current.visibility/1000).toFixed(1)} km`; renderForecast(data); }
async function searchWeather(city) { statusMessage.textContent='Finding the latest conditions...'; weatherInfo.classList.add('loading'); try { const locationResponse=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(city)}&count=1&language=en&format=json`); const locationData=await locationResponse.json(); if (!locationData.results?.length) throw new Error('City not found. Try a nearby city or region.'); const location=locationData.results[0]; const weatherResponse=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${location.latitude}&longitude=${location.longitude}&current=temperature_2m,relative_humidity_2m,apparent_temperature,weather_code,wind_speed_10m,visibility&daily=weather_code,temperature_2m_max,temperature_2m_min&timezone=auto`); if (!weatherResponse.ok) throw new Error('Weather service is unavailable right now.'); renderWeather(location,await weatherResponse.json()); statusMessage.textContent=''; } catch (error) { statusMessage.textContent=error.message; } finally { weatherInfo.classList.remove('loading'); } }
searchForm.addEventListener('submit',event => { event.preventDefault(); const city=cityInput.value.trim(); if(city) searchWeather(city); });
document.getElementById('todayLabel').textContent=new Date().toLocaleDateString('en-US',{weekday:'long',month:'short',day:'numeric'}).toUpperCase(); searchWeather('New York');